version: "3.9"
networks:
  my_network:
    driver: bridge
services:
  db:
    image: mysql:8.0.31
    networks:
      - my_network
    container_name: db
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: Root8888
      MYSQL_DATABASE: nestjs_project
      LANG: C.UTF-8
    ports:
      - 3306:3306
    volumes:
      - C:/Users/htv-Vinhnc/Documents/mysql:/var/lib/mysql/
  app:
    build: 
      dockerfile: ./Dockerfile
    networks:
      - my_network
    container_name: app
    restart: always
    depends_on:
      - db
    ports: 
      - 3000:3000
